# Generated by Django 5.2.6 on 2025-09-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_firebase_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
