# Generated by Django 5.2.6 on 2025-10-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
    ]
